### ISSUE TITLE
Heading and Sub-Heading text misbehaving in Safari on OS X 

### ISSUE THREAD

**Issue by skishchampi** [Chicago/food-inspections-evaluation#54]
Safari behaviour: https://www.dropbox.com/s/o5j5pa7gmxbfwux/Recording%20%232.mp4?dl=0

Expected behavior: https://www.dropbox.com/s/yjyvg98h08a6tyw/Recording%20%233.mp4?dl=0

**Comment by tomschenkjr** [comment]
Fixed.
