### ISSUE TITLE
Add attribution to League of Moveable Type

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/food-inspections-evaluation#55]
- [x] Ensure chicago/journal-chicago#1 has been completed
- [x] Add reference to [OFL license](https://github.com/theleagueof/league-spartan/blob/master/ofl.markdown) to the gh-pages branch LICENSE.md file (which uses the League Spartan font)
- [x] Add reference to League Spartan in gh-pages footer
- [x] Add reference to glyphicons [CC BY 3.0](http://creativecommons.org/licenses/by/3.0/) license to the gh-pages branch's LICENSE.md file
- [x] Add reference to [glyphicons](http://glyphicons.com/license/) in the gh-pages footer

**Comment by geneorama** [comment]
@tomschenkjr the branch `iss55` is 281 commits ahead, 225 commits behind master. I tried comparing the branch to master, but it says that the commit history is completely different.  So, can the branch `iss55` be safely deleted?

**Comment by tomschenkjr** [comment]
Yes.

_
Tom Schenk Jr.
Chief Data Officer
Department of Innovation and Technology
City of Chicago
tom.schenk@cityofchicago.org
312-744-2770



On Thu, Mar 10, 2016 at 3:21 PM -0800, "Gene Leynes" <notifications@github.com<mailto:notifications@github.com>> wrote:


@tomschenkjr<https://github.com/tomschenkjr> the branch iss55 is 281 commits ahead, 225 commits behind master. I tried comparing the branch to master, but it says that the commit history is completely different. So, can the branch iss55 be safely deleted?

-
Reply to this email directly or view it on GitHub<https://github.com/Chicago/food-inspections-evaluation/issues/55#issuecomment-195094497>.


________________________________
This e-mail, and any attachments thereto, is intended only for use by the addressee(s) named herein and may contain legally privileged and/or confidential information. If you are not the intended recipient of this e-mail (or the person responsible for delivering this document to the intended recipient), you are hereby notified that any dissemination, distribution, printing or copying of this e-mail, and any attachment thereto, is strictly prohibited. If you have received this e-mail in error, please respond to the individual sending the message, and permanently delete the original and any copy of any e-mail and printout thereof.
