### ISSUE TITLE
What is the actual operational product

### ISSUE THREAD

**Issue by fgregg** [Chicago/food-inspections-evaluation#63]
It seems like the final operational product should be some sort of prioritized list, but I don't see any code to generate anything like that. How does the model get turned into that product?

**Comment by geneorama** [comment]
The predictions are attached to the data in the 30 script.
https://github.com/Chicago/food-inspections-evaluation/blob/master/CODE/30_glmnet_model.R#L123

The results are delivered as a list of food establishments with their corresponding score, just as it is shown in this evaluation period.  However, this work represents a snapshot in time that was used to evaluate the efficacy of the model, and it is not intended to be an ongoing real time list.

**Comment by fgregg** [comment]
This repo does not represent an ongoing effort? 

So, this: https://twitter.com/ChicagoCDO/status/598951252307922944

is not happening?

**Comment by fgregg** [comment]
Now i understand that this repo contains the current model and is aimed at improving that model. Noted that in the README that's in my PR.
