### ISSUE TITLE
Availability of Inspectors Information 

### ISSUE THREAD

**Issue by mheadd** [Chicago/food-inspections-evaluation#66]
The README file [says](https://github.com/Chicago/food-inspections-evaluation#data) that both weather data and "inspectors information" are not available in the open data portal. But the [website](https://github.com/Chicago/food-inspections-evaluation/blob/gh-pages/index.html#L205) for the project says that only the weather data is not available. 

Is the "inspector information " available on the portal? If not, can you give a sense of what it is?

Thanks!

**Comment by tomschenkjr** [comment]
The README is correct: both the inspectors and weather aren't on the portal; however, the data is made [available in the repo](https://github.com/Chicago/food-inspections-evaluation/blob/master/DATA/inspectors.Rds).

Inspectors aren't released individually in the file (to avoid direct identification), but are grouped into 6 groups to be included in the analysis, so they can be used to either replicate our findings or be used to benchmark alternative models.

As an immediate fix, will update the language on gh-pages to match.

**Comment by senjed** [comment]
Is the inspector data available for more recent inspections?

**Comment by geneorama** [comment]
No unfortunately it's not. You may be able to get that information through a FOIA request to the City of Chicago Department of Public Health.
