### ISSUE TITLE
Document Ubuntu dependencies somewhere

### ISSUE THREAD

**Issue by orborde** [Chicago/food-inspections-evaluation#68]
James Salvatore and I were trying to get the scripts running tonight at ChiHackNight. We both run Ubuntu, and we discovered that you need to run the following before trying to use 00_Startup.R:

sudo apt-get install libssl-dev libcurl4-gnutls-dev libxml2-dev

There may be other Ubuntu dependencies, too.

Maybe it would be helpful to mention the above dependencies in the README, or in comments in 00_Startup.R, so that future users will save time.

**Comment by geneorama** [comment]
Ah yes, thanks.  I think these are needed for `devtools`, which downloads packages from github.  Perhaps `RSocrata`'s dependency on `httr` uses them also.

**Comment by geneorama** [comment]
@tomschenkjr I put in some new documentation and created a pull request from dev to master.  If you accept it, would you also close this issue?

**Comment by tomschenkjr** [comment]
@geneorama [Here is how you can auto-close](https://help.github.com/articles/closing-issues-via-commit-messages/). I'll take care of it on the merge.
