### ISSUE TITLE
Would you mind adding a license to the code?

### ISSUE THREAD

**Issue by t-pfaff** [Chicago/food-inspections-evaluation#78]
A replication of the Food Inspection Forecasting project could be a great entry for contests like the [ODI's Summer Showcase](http://theodi.org/summer-showcase). However, their Terms and Conditions require that no rights are infringed. If you don't add a license the default copyright license applies (see [here](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license)).
In case you want to allow reproduction of your code you could add a MIT license (see [here](https://github.com/blog/1530-choosing-an-open-source-license) how this works for Github).
Do you want to do that?

**Comment by tomschenkjr** [comment]
We have the MIT license listed in the [LICENSE.md](https://github.com/Chicago/food-inspections-evaluation/blob/master/LICENSE.md) file -- or am I missing something?

**Comment by t-pfaff** [comment]
Sorry, I had only looked in the Readme.md.
Nevermind!

**Comment by tomschenkjr** [comment]
No problem.
