### ISSUE TITLE
bad characters in inspectors data (trivial)

### ISSUE THREAD

**Issue by cash** [Chicago/food-inspections-evaluation#83]
This doesn't affect the current workflow, but there are 3 address lines in the inspectors data table that have invalid characters:

```R
> inspectors <- readRDS("DATA/inspectors.Rds")
> inspectors[c(14197, 14198, 18725), Address]
[1] "119\xff E 75 ST CHICAGO, IL 60619 "    
[2] "119\xff E 75 ST CHICAGO, IL 60619 "    
[3] "2444\xff N CLARK ST CHICAGO, IL 60614 "
```
Notice the \xff character after the street number.

Fix:
```R
inspectors[14197, Address:="119 E 75 ST CHICAGO, IL 60619 "]
inspectors[14198, Address:="119 E 75 ST CHICAGO, IL 60619 "]
inspectors[18725, Address:="2444 N CLARK ST CHICAGO, IL 60614 "]
saveRDS(inspectors, "DATA/inspectors.Rds")
```

I'm working on getting approval to sign the CLA.

**Comment by geneorama** [comment]
That's weird.  I think the data was originally copied out of a web browser before we had the live feed.  I can't even remember anymore.  Anyway, I think a manual fix is in order.  I'll just do it unless you want to do the CLA / pull request.
