### ISSUE TITLE
Website header area is off-center

### ISSUE THREAD

**Issue by stevevance** [Chicago/food-inspections-evaluation#84]
Safari, Mac (latest versions for both)
![screenshot 2016-02-07 13 04 46](https://cloud.githubusercontent.com/assets/1330459/12874548/6df72156-cd9b-11e5-80d4-55c2c4f771a6.png)

**Comment by tomschenkjr** [comment]
Fixed with 43e552fbacadf017deb73c390928b62da8c511ce

Thanks!
